FROM node:18.12-alpine3.15 as builder

RUN mkdir -p /frontend
WORKDIR /frontend
COPY public /frontend/public
COPY src /frontend/src
COPY package.json /frontend
COPY tsconfig.json /frontend
RUN npm install
RUN npm run build

FROM nginx:1.23.2-alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /home/frontend/build
COPY --from=builder /frontend/build /usr/share/nginx/html