version: "3.9"
services:
  api:
    env_file:
      - ./mongo/mongo.env
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/api/src
    links:
      - mongo
    restart: "always"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: "always"
  mongo:
    env_file:
      - ./mongo/mongo.env
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongo/data:/data/db
    restart: "always"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    links:
      - api
      - frontend
    ports:
      - 3000:80
    restart: "always"